# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|
  config.vm.define "maas" do |maas|
    maas.vm.box = "bento/ubuntu-16.04"
	maas.vm.box_version = "2.3.8"
	# managed subnet
	maas.vm.network "private_network", ip: "192.168.10.2"
    maas.vm.provider "virtualbox" do |virtualbox|
      #This is to increase memory
      virtualbox.memory = 2048
      virtualbox.cpus = 2
      virtualbox.gui = true
      virtualbox.customize ["modifyvm", :id, "--usb", "on"]      
    end
    maas.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y software-properties-common
      apt-add-repository -y ppa:ansible/ansible
      apt-get update
      apt-get install -y ansible
	  SHELL
  end
end